services:
  api_gateway:
    build: ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
  db_microservice:
    build: ./db-microservice
    volumes:
      - ./db-microservice/src:/usr/src/app/src
    command: npm run start:dev
  auth_microservice:
    build: ./auth-microservice
    volumes:
      - ./auth-microservice/src:/usr/src/app/src
    command: npm run start:dev
  nats:
    image: nats
    ports:
      - 4222:4222
  postgres_db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cdr
      POSTGRES_HOST_AUTH_METHOD: trust